In [1]:
import numpy as np
import pandas as pd

In [2]:
x = [1,2,3,5,1,2]
nx=np.array(x)

In [3]:
print(nx)

[1 2 3 5 1 2]


In [4]:
print(nx.shape)

(6,)


In [5]:
ny = np.array([[1,2,3],[4,5,6]])

In [6]:
print(ny.shape)

(2, 3)


In [7]:
ny

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
one = np.arange(1,100,.2)
one

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [9]:
print(one.size)

495


In [10]:
two = np.linspace(0,100,200)
two

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [11]:
n3 = np.random.rand(100)

In [12]:
n3

array([0.3078461 , 0.63017961, 0.06435599, 0.29805347, 0.27397881,
       0.464442  , 0.9657666 , 0.73595506, 0.27273967, 0.21129854,
       0.10558104, 0.93668566, 0.66643554, 0.22259183, 0.6733784 ,
       0.82640871, 0.89548282, 0.72763083, 0.74991394, 0.90124151,
       0.24655525, 0.9254145 , 0.76058605, 0.30308564, 0.58034781,
       0.0276341 , 0.84764949, 0.62313358, 0.69204797, 0.12203989,
       0.23181636, 0.96878776, 0.38007641, 0.73702033, 0.30555674,
       0.34938496, 0.04428722, 0.67085449, 0.73468948, 0.92624493,
       0.01291511, 0.38342748, 0.1619553 , 0.29639937, 0.99878843,
       0.95809564, 0.66364843, 0.02278709, 0.04566819, 0.80333468,
       0.01204029, 0.66835392, 0.97455126, 0.96971522, 0.02177058,
       0.26324999, 0.39864561, 0.5901178 , 0.41325469, 0.70879631,
       0.80915802, 0.36611809, 0.96025837, 0.4655184 , 0.65021465,
       0.4144007 , 0.76709905, 0.35365237, 0.93802028, 0.05893648,
       0.43148813, 0.15677564, 0.9296797 , 0.41859782, 0.24108

In [13]:
n4 = np.random.randint(1,10,100)
n4

array([9, 4, 7, 9, 4, 8, 5, 7, 2, 5, 1, 7, 9, 7, 2, 2, 9, 3, 9, 2, 2, 8,
       3, 8, 8, 9, 3, 9, 8, 4, 1, 5, 7, 2, 6, 9, 2, 5, 5, 2, 7, 9, 7, 1,
       3, 6, 1, 8, 4, 4, 3, 3, 4, 9, 5, 3, 7, 1, 2, 6, 6, 3, 5, 2, 4, 5,
       2, 9, 5, 1, 2, 9, 8, 3, 9, 5, 9, 6, 2, 6, 5, 4, 7, 8, 4, 2, 7, 3,
       9, 3, 6, 6, 8, 1, 8, 7, 1, 8, 3, 6])

In [14]:
n4.reshape((10,10))


array([[9, 4, 7, 9, 4, 8, 5, 7, 2, 5],
       [1, 7, 9, 7, 2, 2, 9, 3, 9, 2],
       [2, 8, 3, 8, 8, 9, 3, 9, 8, 4],
       [1, 5, 7, 2, 6, 9, 2, 5, 5, 2],
       [7, 9, 7, 1, 3, 6, 1, 8, 4, 4],
       [3, 3, 4, 9, 5, 3, 7, 1, 2, 6],
       [6, 3, 5, 2, 4, 5, 2, 9, 5, 1],
       [2, 9, 8, 3, 9, 5, 9, 6, 2, 6],
       [5, 4, 7, 8, 4, 2, 7, 3, 9, 3],
       [6, 6, 8, 1, 8, 7, 1, 8, 3, 6]])

In [15]:
n5 = n4.reshape((25,4))

In [16]:
n1 = np.random.randint(1,10,(5,5))
n2 = np.random.randint(1,10,(5,5))

In [17]:
n1 + n2

array([[12, 11, 14, 16, 11],
       [ 3,  7, 14,  9,  9],
       [ 7, 12, 10, 11, 12],
       [ 5, 14, 10,  2,  5],
       [ 9, 10, 12, 10,  7]])

In [18]:
n1 - n2

array([[ 0,  3,  0,  2, -5],
       [ 1,  3, -2,  1, -1],
       [ 1, -2,  6,  1,  0],
       [ 3,  0,  0,  0,  3],
       [ 1, -4, -4,  6,  1]])

In [19]:
n1 / n2

array([[1.        , 1.75      , 1.        , 1.28571429, 0.375     ],
       [2.        , 2.5       , 0.75      , 1.25      , 0.8       ],
       [1.33333333, 0.71428571, 4.        , 1.2       , 1.        ],
       [4.        , 1.        , 1.        , 1.        , 4.        ],
       [1.25      , 0.42857143, 0.5       , 4.        , 1.33333333]])

In [20]:
n2 ** n2

array([[   46656,      256,   823543,   823543, 16777216],
       [       1,        4, 16777216,      256,     3125],
       [      27,   823543,        4,     3125,    46656],
       [       1,   823543,     3125,        1,        1],
       [     256,   823543, 16777216,        4,       27]])

In [21]:
n1 ** 4

array([[1296, 2401, 2401, 6561,   81],
       [  16,  625, 1296,  625,  256],
       [ 256,  625, 4096, 1296, 1296],
       [ 256, 2401,  625,    1,  256],
       [ 625,   81,  256, 4096,  256]], dtype=int32)

In [22]:
n1 + 10

array([[16, 17, 17, 19, 13],
       [12, 15, 16, 15, 14],
       [14, 15, 18, 16, 16],
       [14, 17, 15, 11, 14],
       [15, 13, 14, 18, 14]])

In [23]:
n1.dot(n2)

array([[ 85, 171, 181, 120, 143],
       [ 56, 123, 123,  77,  94],
       [ 83, 166, 162, 106, 129],
       [ 63, 100, 131,  90, 110],
       [ 69, 138, 139,  83,  99]])

In [24]:
n1 * n2

array([[36, 28, 49, 63, 24],
       [ 2, 10, 48, 20, 20],
       [12, 35, 16, 30, 36],
       [ 4, 49, 25,  1,  4],
       [20, 21, 32, 16, 12]])

In [25]:
n6 = np.random.randint(1,10,10)
n6

array([9, 3, 7, 2, 1, 1, 4, 8, 4, 8])

In [26]:
n6[0]

9

In [27]:
n6[1]

3

In [28]:
n6[-1]

8

In [29]:
n6[:5]

array([9, 3, 7, 2, 1])

In [30]:
n6[5:]

array([1, 4, 8, 4, 8])

In [31]:
# flatten a n dimen matrix to 1 dimen matrix
n5.flatten()

array([9, 4, 7, 9, 4, 8, 5, 7, 2, 5, 1, 7, 9, 7, 2, 2, 9, 3, 9, 2, 2, 8,
       3, 8, 8, 9, 3, 9, 8, 4, 1, 5, 7, 2, 6, 9, 2, 5, 5, 2, 7, 9, 7, 1,
       3, 6, 1, 8, 4, 4, 3, 3, 4, 9, 5, 3, 7, 1, 2, 6, 6, 3, 5, 2, 4, 5,
       2, 9, 5, 1, 2, 9, 8, 3, 9, 5, 9, 6, 2, 6, 5, 4, 7, 8, 4, 2, 7, 3,
       9, 3, 6, 6, 8, 1, 8, 7, 1, 8, 3, 6])

In [32]:
# flatten a n dimen matrix to 1 dimen matrix
n5.ravel()

array([9, 4, 7, 9, 4, 8, 5, 7, 2, 5, 1, 7, 9, 7, 2, 2, 9, 3, 9, 2, 2, 8,
       3, 8, 8, 9, 3, 9, 8, 4, 1, 5, 7, 2, 6, 9, 2, 5, 5, 2, 7, 9, 7, 1,
       3, 6, 1, 8, 4, 4, 3, 3, 4, 9, 5, 3, 7, 1, 2, 6, 6, 3, 5, 2, 4, 5,
       2, 9, 5, 1, 2, 9, 8, 3, 9, 5, 9, 6, 2, 6, 5, 4, 7, 8, 4, 2, 7, 3,
       9, 3, 6, 6, 8, 1, 8, 7, 1, 8, 3, 6])

In [33]:
x = np.random.randint(1,10,(5,5))

In [34]:
x.transpose() # transpose the matrix , row to column and column to row

array([[4, 7, 4, 1, 9],
       [8, 7, 8, 6, 4],
       [1, 2, 5, 9, 3],
       [9, 7, 2, 8, 7],
       [6, 6, 4, 4, 4]])

In [35]:
x.T # transpose the matrix , row to column and column to row

array([[4, 7, 4, 1, 9],
       [8, 7, 8, 6, 4],
       [1, 2, 5, 9, 3],
       [9, 7, 2, 8, 7],
       [6, 6, 4, 4, 4]])

In [36]:
n6

array([9, 3, 7, 2, 1, 1, 4, 8, 4, 8])

In [37]:
n6.max()

9

In [38]:
n6.mean()

4.7

In [39]:
n6.sum()

47

In [40]:
n5.sum() # sum all all values

517

In [41]:
n5.sum(axis=0) # sum all values in each column

array([144, 120, 111, 142])

In [42]:
n5.sum(axis=1) # sum all values in each row

array([29, 24, 15, 20, 23, 21, 29, 18, 24, 14, 24, 18, 14, 21, 16, 16, 20,
       17, 25, 23, 24, 16, 24, 24, 18])

In [43]:
print(n6, n6.max(),"found at index", n6.argmax())
print(n6, n6.min(),"found at index", n6.argmin())

[9 3 7 2 1 1 4 8 4 8] 9 found at index 0
[9 3 7 2 1 1 4 8 4 8] 1 found at index 4


In [44]:
n6.argmax() # the index of the max value

0

In [45]:
a = np.random.randint(1,100, (3,2))
b = np.random.randint(1,100, (3,2))
c = np.random.randint(1,100, (2,3))

print(a)
print(b)
print(c)

[[40 31]
 [15 83]
 [60  4]]
[[79  5]
 [79 30]
 [67 37]]
[[ 2 25 78]
 [20 12 53]]


In [46]:
np.hstack((a,b)) # horizontal stack

array([[40, 31, 79,  5],
       [15, 83, 79, 30],
       [60,  4, 67, 37]])

In [47]:
np.vstack((a,b)) # vertical stack

array([[40, 31],
       [15, 83],
       [60,  4],
       [79,  5],
       [79, 30],
       [67, 37]])

In [48]:
np.vstack((a, c.T))

array([[40, 31],
       [15, 83],
       [60,  4],
       [ 2, 20],
       [25, 12],
       [78, 53]])

In [49]:
m = np.array([1,2,3,4,2,2,3,5,6,1,2,2,3,5,6,1,2,3,5,6,2,4,5,6,3,1,2,3,5,7,6,8,9])

In [50]:
# boolean filter
m > 5

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True,  True,  True,  True])

In [51]:
m[m > 5]

array([6, 6, 6, 6, 7, 6, 8, 9])

In [52]:
m[m != 2]

array([1, 3, 4, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6, 4, 5, 6, 3, 1, 3, 5, 7,
       6, 8, 9])

In [53]:
# in range of 2 to 8
m[(m > 2) & (m < 8)]

array([3, 4, 3, 5, 6, 3, 5, 6, 3, 5, 6, 4, 5, 6, 3, 3, 5, 7, 6])

In [56]:
# user created numpy matrix
mat = []
for i in range(10):
    mat.append(int(input('Enter value')))
mat = np.array(mat)

In [58]:
print(mat, mat.shape)

[2 3 1 2 4 6 6 3 2 1] (10,)


In [59]:
# user created numpy matrix
mat= []
for i in range(2):
    smat = []
    for j in range(3):
        smat.append(int(input('Enter value')))
    mat.append(smat)
mat = np.array(mat)
print(mat, mat.shape)

[[3 2 5]
 [2 1 2]] (2, 3)
